# Generated by Django 3.2.2 on 2022-07-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
