# Generated by Django 3.2.2 on 2022-08-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_forma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='forma',
            new_name='form',
        ),
    ]
