# Generated by Django 3.2.2 on 2022-08-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_forma_book_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='form',
            new_name='forma',
        ),
    ]
