# Generated by Django 3.2.2 on 2022-08-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_form_book_forma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='forma',
        ),
    ]
