# Generated by Django 3.2.2 on 2022-08-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_forma'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='medio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
