# Generated by Django 3.2.2 on 2022-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fecha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='hora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
