# Generated by Django 3.2.2 on 2022-08-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20220802_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fecha',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='hora',
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
    ]
