# Generated by Django 3.2.2 on 2022-08-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20220802_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
