# Generated by Django 3.2.2 on 2022-08-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
