# Generated by Django 3.2.2 on 2022-08-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
