# Generated by Django 3.2.2 on 2022-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
