# Generated by Django 3.2.2 on 2022-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
