# Generated by Django 3.2.2 on 2022-08-12 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='users/user_default_profile.png', upload_to=services.models.company_directory_path_profile)),
                ('banner', models.ImageField(default='users/user_default_bg.jpg', upload_to=services.models.company_directory_path_banner)),
                ('description', models.TextField(max_length=400)),
                ('category', models.CharField(blank=True, choices=[('Turismo', 'Turismo'), ('Deporte', 'Deporte'), ('Estudio', 'Estudio'), ('Voluntariados', 'Voluntariados'), ('Arte', 'Arte'), ('Cultura', 'Cultura'), ('Automotriz', 'Automotriz'), ('Emprendimiento', 'Emprendimiento'), ('Entretenimiento', 'Entretenimiento')], max_length=100, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=False)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('urlChat', models.URLField(blank=True, null=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='nocustomers', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='customers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
