# Generated by Django 3.2.2 on 2022-08-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_company_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='slug',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
