# Generated by Django 3.2.2 on 2022-08-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220812_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='name',
        ),
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
