# Generated by Django 3.2.2 on 2022-08-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_slug_empresa_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre',
            new_name='slug',
        ),
    ]
