# Generated by Django 3.2.2 on 2022-08-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_nombre_empresa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='slug',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
