# Generated by Django 3.2.2 on 2022-08-13 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20220812_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=services.models.work_directory_path)),
                ('presentation', models.TextField(max_length=400)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.empresa')),
            ],
        ),
    ]
