# Generated by Django 3.2.2 on 2022-08-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_work_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
