# Generated by Django 3.2.2 on 2022-08-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_work_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
