# Generated by Django 3.2.2 on 2022-08-13 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_work_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
