# Generated by Django 3.2.2 on 2022-08-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20220813_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='verified',
            field=models.CharField(choices=[('unverified', 'unverified'), ('verified', 'verified')], default='unverified', max_length=10),
        ),
    ]
