# Generated by Django 3.2.2 on 2022-08-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_empresa_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
