# Generated by Django 3.2.2 on 2022-08-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20220813_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='slug',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.SlugField(unique=True),
        ),
    ]
