# Generated by Django 3.2.2 on 2022-08-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_empresa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='slug',
        ),
    ]
