# Generated by Django 3.2.2 on 2022-08-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_empresa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
