# Generated by Django 3.2.2 on 2022-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_empresa_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
