# Generated by Django 3.2.2 on 2022-08-16 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import services.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0022_alter_work_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.models.homework_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='category',
            field=models.CharField(blank=True, choices=[('Turismo', 'Turismo'), ('Educacion', 'Educación'), ('Tecnologia', 'Tecnologia'), ('Aseo', 'Aseo'), ('Moda', 'Moda'), ('Artesania', 'Artesania'), ('Automotriz', 'Automotriz'), ('Gastronomia', 'Gastronomía'), ('Entretenimiento', 'Entretenimiento'), ('Inmobiliaria', 'Inmobiliaria'), ('Seguridad', 'Seguridad')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.TextField(max_length=400)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('Work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.work')),
                ('image', models.ManyToManyField(blank=True, to='services.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerHomework', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
