# Generated by Django 3.2.2 on 2022-08-16 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0023_auto_20220816_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.TextField(max_length=400)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('Work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.work')),
                ('image', models.ManyToManyField(blank=True, to='services.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerHomework', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
