# Generated by Django 3.2.2 on 2022-08-16 23:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0024_auto_20220816_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeworkModel',
            new_name='Homework',
        ),
    ]
