# Generated by Django 3.2.2 on 2022-08-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_rename_homeworkmodel_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='Work',
            new_name='slugWork',
        ),
    ]
