# Generated by Django 3.2.2 on 2022-08-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_rename_work_homework_slugwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='slugWork',
            new_name='work',
        ),
    ]
