# Generated by Django 3.2.2 on 2022-08-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_rename_slugwork_homework_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='accepted',
            field=models.CharField(choices=[('Enviada', 'Enviada'), ('En_revision', 'En revisión'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Enviada', max_length=100),
        ),
    ]
