# Generated by Django 3.2.2 on 2022-08-04 17:19

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_rename_miembros_group_numero_miembros'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=groups.models.group_directory_path),
        ),
    ]
