# Generated by Django 3.2.2 on 2022-08-05 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0007_group_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.TextField()),
                ('why', models.TextField()),
                ('hope', models.TextField()),
                ('group', models.ManyToManyField(to='groups.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
