# Generated by Django 3.2.2 on 2022-08-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_postulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(blank=True, choices=[('Turismo', 'Turismo'), ('Deporte', 'Deporte'), ('Estudio', 'Estudio'), ('Voluntariados', 'Voluntariados'), ('Arte', 'Arte'), ('Cultura', 'Cultura'), ('Automotriz', 'Automotriz'), ('Emprendimiento', 'Emprendimiento'), ('Entretenimiento', 'Entretenimiento')], max_length=100, null=True),
        ),
    ]
