# Generated by Django 3.2.2 on 2022-08-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_auto_20220806_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
