# Generated by Django 3.2.2 on 2022-08-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_postulation_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulation',
            old_name='active',
            new_name='acceted',
        ),
    ]
