# Generated by Django 3.2.2 on 2022-08-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_rename_active_postulation_acceted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulation',
            old_name='acceted',
            new_name='accepted',
        ),
    ]
