# Generated by Django 3.2.2 on 2022-08-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_rename_acceted_postulation_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='accepted',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=100),
        ),
    ]
