# Generated by Django 3.2.2 on 2022-08-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_alter_postulation_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulation',
            old_name='user',
            new_name='postulant',
        ),
    ]
