# Generated by Django 3.2.2 on 2022-08-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_rename_user_postulation_postulant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulation',
            old_name='postulant',
            new_name='user',
        ),
    ]
