# Generated by Django 3.2.2 on 2022-08-11 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_auto_20220808_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='date_created',
        ),
        migrations.AddField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
