# Generated by Django 3.2.2 on 2022-08-11 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_auto_20220810_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
