# Generated by Django 3.2.2 on 2022-08-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_postulation_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
